# Generated by Django 4.2.9 on 2024-07-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rad_content',
            name='id',
        ),
        migrations.AddField(
            model_name='rad_content',
            name='rad_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='paragraph2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='paragraph3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='paragraph4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
