# Generated by Django 4.2.9 on 2024-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_rad_content_id_rad_content_rad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad_content',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/radCard_image/'),
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/radCard_image/'),
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/radCard_image/'),
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/radCard_image/'),
        ),
    ]
