# Generated by Django 4.2.9 on 2024-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_rad_content_image1_alter_rad_content_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad_content',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/radCard_image/'),
        ),
    ]
