# Generated by Django 4.2.9 on 2024-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_rad_content_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad_content',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
