# Generated by Django 4.2.9 on 2024-07-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rad_content_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rad_content',
            name='header_sub',
        ),
        migrations.AlterField(
            model_name='rad_content',
            name='header_main',
            field=models.CharField(max_length=50),
        ),
    ]
